const express = require('express')
const httpContext = require('express-http-context');
const app = express()
const cors = require('cors');
const {v4: uuidv4} = require('uuid');
const apiRouter = express.Router();
const apiRouterAuth = express.Router();
const fs = require('fs');
const path = require('path');
const {GoogleSpreadsheet: GoogleSpreadsheet} = require('google-spreadsheet');
const {JWT: JWT} = require('google-auth-library');

let sheet;

app.use(cors({
    origin: 'http://localhost:4200'
}));
app.use(express.json());

function getUser(token) {
    const tokens = readTokens();
    if (tokens[token]) {
        return tokens[token];
    }
    throw new Error('No user');
}

function getContextVars() {
    return {
        environment: httpContext.get('environment'),
        token: httpContext.get('token'),
    }
}

async function readData() {
    const {environment} = getContextVars();
    const rows = await sheet.getRows();
    const a = rows[0].get('data');
    return JSON.parse(a);
}

async function writeData(token, items) {
    const {environment} = getContextVars();
    const filtered = items.filter(e => e.boughtAt === null || e.boughtAt === undefined || new Date(e.boughtAt).getTime() > new Date().getTime() - 1000 * 60 * 60 * 24);
    
    const rows = await sheet.getRows();
    rows[0].set('data', JSON.stringify(filtered));
    await rows[0].save();
}

async function addSuggestion(suggestion) {
    console.log('addSuggestion', suggestion);
    const {environment} = getContextVars();
    const suggestions = await readSuggestions();
    if (!suggestions.includes(suggestion)) {
    
        const rows = await sheet.getRows();
        rows[0].set('suggestions', JSON.stringify([suggestion, ...suggestions]));
        await rows[0].save();
    }
}

function readTokens() {
    try {
        return JSON.parse(fs.readFileSync('tokens.json', 'utf8'));
    } catch (err) {
        return [];
    }
}

async function readSuggestions() {
    const {environment} = getContextVars();
    const rows = await sheet.getRows();
    const a = rows[0].get('suggestions');
    console.log('aaa', a);
    return JSON.parse(a);
}

apiRouterAuth.use(httpContext.middleware);
apiRouterAuth.use((req, res, next) => {
    const environment = req.headers.environment;
    const token = req.headers.token;
    const tokens = readTokens();
    if (tokens[environment] && tokens[environment][token]) {
        httpContext.set('environment', environment);
        httpContext.set('token', token);
        next();
    } else {
        const err = new Error('Forbidden');
        err.status = 403;
        next(err);
    }
})

apiRouterAuth.get('/items', function (req, res) {
    readData().then(r => {
        res.json(r);
    });
});
apiRouterAuth.post('/items', function (req, res) {
    readData(req.headers.token).then(async (items) => {
        const body = req.body;
        const newItem = {
            "name": body.name,
            "id": uuidv4(),
            "boughtAt": null,
        };
        items.unshift(newItem);
        console.log('items to save');
        console.log(items);
        await Promise.all([writeData(req.headers.token, items), addSuggestion( newItem.name)]);
        res.json(newItem);
    });
});
apiRouterAuth.patch('/items/:id', async function (req, res) {
    const id = req.params.id;
    const body = req.body;

    const items = await readData(req.headers.token);
    const altered = items.map(e => {
        if (e.id === id) {
            return {
                ...e,
                name: body.name,
                boughtAt: body.boughtAt,
            }
        }
        return e;
    });
    await writeData(req.headers.token, altered);
    await addSuggestion(req.headers.token, body.name);
    return res.json(altered.find(e => e.id === id));
});
apiRouterAuth.delete('/items/:id', async function (req, res) {
    const id = req.params.id;

    const items = await readData(req.headers.token);
    const altered = items.filter(e => e.id !== id);
    await writeData(req.headers.token, altered);
    return res.send();
});
apiRouterAuth.get('/suggestions', function (req, res) {
    readSuggestions(req.headers.token).then(r => res.json(r));
});

apiRouter.post('/login', function (req, res) {
    const environment = req.body.environment;
    const token = req.body.token;
    const tokens = readTokens();
    if (tokens[environment] && tokens[environment][token]) {
        return res.json(tokens[environment][token]);
    }
    return res.status(403).send("Unknown token");
});

app.use('/api', apiRouter);
apiRouter.use('/auth', apiRouterAuth);

app.use(express.static('static/generated'))
app.get('*', (req, res) => {
    res.sendFile(path.join(__dirname, 'static/generated/index.html'));
});

console.log(process.env);
console.log(process.env.MAIL);
console.log(process.env.KEY);

const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: process.env.MAIL,
  key: process.env.KEY.replace(/\\n/g, "\n"),
  scopes: ['https://www.googleapis.com/auth/spreadsheets'],
});

const doc = new GoogleSpreadsheet('1NKP-KxYkPZkreImnjUXMiE1KQudjhiwYeZlS6Vf90tg', serviceAccountAuth);
(async function () {
    await doc.loadInfo(); // loads document properties and worksheets
    console.log(doc.title);
    sheet = doc.sheetsByIndex[0];
    app.listen(3000)

    console.log('listening on 3000');
})();
